### ISSUE TITLE
Problema al concretar las decargas

### ISSUE THREAD

**Issue by M4rckR** [ivansaul/platzi-downloader#1]
# Tengo todos lo requerimientos instalados
- Seguir a la par todos los pasos brindados, sin embargo al momentos de llegar a cierto punto me sale un problema de este estilo:
![image](https://github.com/ivansaul/platzi-downloader/assets/121461431/7da61078-ecb7-439f-81d4-55505ca41425)

**Comment by ivansaul** [comment]
@M4rckR veo que si logro generar en `data.json`. Lo más importante es ese archivo. Por lo que puedes continúa sin mayor inconveniente con `python downloader.py`. El error que estás experimentando al parecer es por qué no se cerró correctamente el controlador.

**Comment by M4rckR** [comment]
> @M4rckR veo que si logro generar en `data.json`. Lo más importante es ese archivo. Por lo que puedes continúa sin mayor inconveniente con `python downloader.py`. El error que estás experimentando al parecer es por qué no se cerró correctamente el controlador.

Entonces seria cuestion de solamente escribir ese comando? o como procederia. (Te lo agradeceria mucho ya que quiero estudiar varias cosas)

**Comment by ivansaul** [comment]
@M4rckR asi sigue con el siguiente comando.

**Comment by M4rckR** [comment]
> @M4rckR asi sigue con el siguiente comando.
Lo ejecute, funciono, sin embargo hay un problema el cual hace que solo em descargue los pdf (Paginas descargas) y solo el primer video:
`
[1 / 13][streaming] Diseño Ético con IA
WARNING: External Downloader arguments given without specifying name. The arguments will be given to aria2c
[generic] Extracting URL: https://mdstrm.com/video/64d643220cea5324c5bc9d6a.m3u8
[generic] 64d643220cea5324c5bc9d6a: Downloading webpage
[generic] 64d643220cea5324c5bc9d6a: Downloading m3u8 information
[generic] 64d643220cea5324c5bc9d6a: Checking m3u8 live status
[info] 64d643220cea5324c5bc9d6a: Downloading 1 format(s): 1430
[download] Curso de Diseño Ético para el Desarrollo de Productos Digitales con IA\1. Diseño Ético e Inteligencia Artificial\1. Diseño Ético con IA.mp4 has already been downloaded
[download] 100% of   11.70MiB
[2 / 13][streaming] Rol y Responsabilidades Éticas del Diseñador de UX en Proyectos de IA
WARNING: External Downloader arguments given without specifying name. The arguments will be given to aria2c
[generic] Extracting URL: https://mdstrm.com/video/64d6432eea7b0b537c001b37.m3u8
[generic] 64d6432eea7b0b537c001b37: Downloading webpage
[generic] 64d6432eea7b0b537c001b37: Downloading m3u8 information
[generic] 64d6432eea7b0b537c001b37: Checking m3u8 live status
[info] 64d6432eea7b0b537c001b37: Downloading 1 format(s): 1011
[hlsnative] Downloading m3u8 manifest
WARNING: Live HLS streams are not supported by the native downloader. If this is a livestream, please add "--downloader ffmpeg --hls-use-mpegts" to your command
[hlsnative] Fragment downloads will be delegated to aria2c
[hlsnative] Total fragments: 35
[download] Destination: Curso de Diseño Ético para el Desarrollo de Productos Digitales con IA\2. Responsabilidad Ética de los Profesionales de Diseño en Proyectos de Inteligencia Artificial\2. Rol y Responsabilidades Éticas del Diseñador de UX en Proyectos de IA.mp4
[download] Writing temporary cookies file to "C:\Users\marco\AppData\Local\Temp\tmpx9fxkkuh.cookies"
ERROR: Unable to download video: [Errno 2] No such file or directory: 'Curso de Diseño Ético para el Desarrollo de Productos Digitales con IA\\2. Responsabilidad Ética de los Profesionales de Diseño en Proyectos de Inteligencia Artificial\\2. Rol y Responsabilidades Éticas del Diseñador de UX en Proyectos de IA.mp4.part.frag.urls'
Traceback (most recent call last):
  File "F:\Platzi\platzi-downloader\downloader.py", line 73, in <module>
    main()
  File "C:\Python311\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Platzi\platzi-downloader\downloader.py", line 70, in main
    dl.dl_course()
  File "F:\Platzi\platzi-downloader\downloader.py", line 49, in dl_course
    self.m3u8_downloader(file_path = file_path, url=url, ext_dwl=self.external_downloader)
  File "F:\Platzi\platzi-downloader\downloader.py", line 30, in m3u8_downloader
    subprocess.run(command, check=True)
  File "C:\Python311\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['yt-dlp', '-f', 'bv+ba/b', '-o', 'Curso de Diseño Ético para el Desarrollo de Productos Digitales con IA/2. Responsabilidad Ética de los Profesionales de Diseño en Proyectos de Inteligencia Artificial/2. Rol y Responsabilidades Éticas del Diseñador de UX en Proyectos de IA.%(ext)s', '--external-downloader', 'aria2c', '--external-downloader-args', '-s 10 -x 10 -k 1M', 'https://mdstrm.com/video/64d6432eea7b0b537c001b37.m3u8']' returned non-zero exit status 1.
`
![image](https://github.com/ivansaul/platzi-downloader/assets/121461431/cb019dfa-c7cb-4b59-bc98-fa0b23394e62)
